services:
  # 数据库服务
  mysql:
    image: mysql:8.0
    container_name: kangyang-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: kangyang
      MYSQL_USER: kangyang
      MYSQL_PASSWORD: kangyang123
      TZ: Asia/Shanghai
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - kangyang-network

  # Redis缓存服务
  redis:
    image: redis:7-alpine
    container_name: kangyang-redis
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 5s
      retries: 5
    networks:
      - kangyang-network

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local

networks:
  kangyang-network:
    driver: bridge