global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'edge-controller-1'
    static_configs:
      - targets: ['edge-controller-1:9090']
  
  - job_name: 'edge-controller-2'
    static_configs:
      - targets: ['edge-controller-2:9090']
      
  - job_name: 'management-backend'
    static_configs:
      - targets: ['management-backend:8080']
