server:
  port: 8080

spring:
  application:
    name: kangyang-fall-detection

  # 数据库配置
  datasource:
    url: jdbc:mysql://${DB_HOST:127.0.0.1}:${DB_PORT:3306}/kangyang?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USER:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ${DB_PASSWORD:123456}

  # JPA配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # Redis配置
  redis:
    host: ${REDIS_HOST:localhost}
    port: 6379
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0

  # JSON配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

# 日志配置
logging:
  level:
    com.kangyang: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# 边缘控制器配置
edge-controllers:
  # 边缘控制器端点配置
  endpoints:
    controller_1: "http://${EDGE_CONTROLLER_1_HOST:localhost}:${EDGE_CONTROLLER_1_PORT:8084}"
    controller_2: "http://${EDGE_CONTROLLER_2_HOST:localhost}:${EDGE_CONTROLLER_2_PORT:8085}"
  # 通信超时设置
  timeout: 10000
  # 心跳超时时间（分钟）
  heartbeat_timeout: 2

# 微信告警配置
wechat:
  enabled: ${WECHAT_ENABLED:true}
  webhook:
    url: ${WECHAT_WEBHOOK_URL:}
  app:
    id: ${WECHAT_APP_ID:}
    secret: ${WECHAT_APP_SECRET:}
  user:
    openid: ${WECHAT_USER_OPENID:}
  template:
    fall: ${WECHAT_TEMPLATE_FALL:}
    fire: ${WECHAT_TEMPLATE_FIRE:}
    smoke: ${WECHAT_TEMPLATE_SMOKE:}

# 告警配置
alert:
  enabled: true
  # 告警规则
  rules:
    fall_detection:
      enabled: true
      severity: HIGH
      cooldown_minutes: 5
    fire_detection:
      enabled: true
      severity: CRITICAL
      cooldown_minutes: 1
    smoke_detection:
      enabled: true
      severity: HIGH
      cooldown_minutes: 3

# Actuator监控端点配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized